sudo: required
dist: xenial
language: c
matrix:
   include:
     - addons:
          postgresql: 10
          apt:
            packages:
               - postgresql-server-dev-10
       env:
          - POSTGRESQL=10
     - addons:
          postgresql: 11
          apt:
            packages:
               - postgresql-11
               - postgresql-client-11
               - postgresql-server-dev-11
       env:
          - POSTGRESQL=11
          - PGPORT=5433
install:
   - sudo make install
   - psql -c 'ALTER SYSTEM set SHARED_PRELOAD_LIBRARIES to pg_stat_statements'
   - sudo service postgresql restart $POSTGRESQL
script:
  - make installcheck
after_failure:
  - cat regression.diffs
